version: "3.9"

services:
  zad-ai-engine:
    image: abourida/docker-zad-ai-engine:latest
    container_name: zad-ai-engine
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - zad-network

  redis:
    image: redis:7-alpine
    container_name: zad-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - zad-network

  voice-agent:
    image: abduh38/livekit-voice-agent:latest
    container_name: zad-voice-agent
    env_file:
      - .env
    environment:
      - RAG_API_URL=http://zad-ai-engine:8000/api/v1/chat/ask
      - RAG_CHUNKS_URL=http://zad-ai-engine:8000/api/v1/chat/chunks
    restart: unless-stopped
    depends_on:
      - zad-ai-engine
    networks:
      - zad-network

networks:
  zad-network:
    driver: bridge

volumes:
  redis_data:
