import os
import json
import logging
from google import genai
from google.genai import types
from dotenv import load_dotenv

# Use the same API keys from mindmap generator for simplicity
from mindmap_generator import api_key_cycle

load_dotenv()
logger = logging.getLogger(__name__)

QUIZ_SYSTEM_PROMPT = """
أنت خبير تربوي متخصص في العلوم الإسلامية، ومهمتك هي اختبار مدى فهم الطالب للنص الذي سأعطيه لك.
قم بإنشاء أسئلة اختيار من متعدد (MCQ) بناءً على النص المُقدم لك فقط.
لا تقم بتأليف معلومات من خارج النص أبداً.

يجب أن تقوم بإرجاع النتيجة على هيئة كائن JSON (JSON Object) حصرياً، بالصيغة التالية:
{
  "questions": [
    {
      "id": "1",
      "question": "نص السؤال هنا؟",
      "options": ["الاختيار الأول", "الاختيار الثاني", "الاختيار الثالث", "الاختيار الرابع"],
      "correct_answer_index": 2,
      "explanation": "شرح لسبب كون هذه الإجابة هي الصحيحة، مع اقتباس أو إشارة لمعنى النص الأصلي."
    }
  ]
}

قواعد هامة جداً:
1. التزم بعدد الأسئلة المطلوب منك في التوجيه (إذا طُلب منك عدد محدد)، أو استخرج العدد الذي تراه مناسباً إذا طُلب منك ذلك.
2. `correct_answer_index` يجب أن يكون رقماً من 0 إلى 3 يمثل الإجابة الصحيحة في مصفوفة الاختيارات.
3. يجب أن تكون الاختيارات 4 فقط.
4. يجب أن يكون `explanation` واضحاً. من الأفضل جداً أن تعزو الإجابة إلى المؤلف والكتاب المذكور في السياق (إن وجد) بدلاً من قول "النص يوضح"، كأن تقول: (لأن الإمام [اسم المؤلف] ذكر في كتابه أن...).
5. لا ترجع أي نص خارج صيغة JSON.
"""

async def generate_quiz_json(chunk_text: str, num_questions: int = 3, metadata: dict = None) -> dict:
    if metadata is None:
        metadata = {}
        
    if not api_key_cycle:
        raise ValueError("GEMINI_API_KEYS is not configured in .env")

    # Fetch the next API key in the cycle
    current_key = next(api_key_cycle)
    client = genai.Client(api_key=current_key)

    author = metadata.get("author")
    context_prefix = f"مؤلف هذا النص هو الإمام '{author}'.\n\n" if author else ""


    if num_questions > 0:
        user_prompt = f"{context_prefix}قم باستخراج {num_questions} أسئلة اختبار من متعدد من النص التالي:\n\n{chunk_text}"
    else:
        user_prompt = f"{context_prefix}قم باستخراج العدد المناسب من أسئلة اختبار من متعدد (بناءً على كثافة المعلومات) من النص التالي:\n\n{chunk_text}"

    try:
        response = await client.aio.models.generate_content(
            model="gemini-2.5-flash",
            contents=user_prompt,
            config=types.GenerateContentConfig(
                system_instruction=QUIZ_SYSTEM_PROMPT,
                temperature=0.3,
                response_mime_type="application/json"
            )
        )
        
        raw_content = response.text.strip()
        
        # Clean up any markdown blocks if generated by mistake
        if raw_content.startswith("```json"):
            raw_content = raw_content[7:]
        elif raw_content.startswith("```"):
            raw_content = raw_content[3:]
            
        if raw_content.endswith("```"):
            raw_content = raw_content[:-3]
            
        raw_content = raw_content.strip()
        
        # Parse JSON
        quiz_data = json.loads(raw_content)
        return quiz_data
        
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse Quiz JSON: {e}")
        logger.error(f"Raw Output: {raw_content}")
        raise ValueError("الذكاء الاصطناعي لم يقم بتوليد JSON صالح للاختبار.")
    except Exception as e:
        logger.error(f"Gemini API Error (Quiz): {e}")
        raise e
